#!/bin/bash
#PBS -N comparemodels
#PBS -q avx
#PBS -l nodes=1:ppn=64
#PBS -e e.$PBS_JOBNAME-$PBS_JOBID
#PBS -o o.$PBS_JOBNAME-$PBS_JOBID


export PATH=/usr/local/bin:$PATH

PROJPATH=/home/sjspielman/leisr_validation/compare_models
DATAPATH=$PROJPATH/enzyme_data
RESULTPATH=$PROJPATH/inference
mkdir -p $RESULTPATH

DATA=$1

HYPATH=/home/sjspielman/hyphy
MP=$HYPATH/HYPHYMP
LIBPATH=$HYPATH/res
BATCHFILE=$LIBPATH/TemplateBatchFiles/LEISR.bf

for MODEL in LG WAG JTT JC69; do
    for RV in Gamma No; do
       if [ $RV == "Gamma" ]; then
	  RV2=G
       else
          RV2=No
       fi 
        JSON=$RESULTPATH/$DATA.$MODEL-$RV2.LEISR.json
        if [ ! -e $JSON ]; then
            $MP LIBPATH=$LIBPATH  $BATCHFILE ${DATAPATH}/$DATA y Protein $MODEL $RV
            mv ${DATAPATH}/$DATA.LEISR.json  $JSON
        fi
    done
done


